name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build Main Site
        run: pnpm run build
        
      - name: Build Publisher
        run: pnpm run build:publisher
        
      - name: Copy 404.html for Publisher
        run: cp public/publisher-404.html dist-publisher/404.html
        
      - name: Create CNAME for Publisher
        run: cp public/publisher-CNAME dist-publisher/CNAME
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Main Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: main-site
          path: './dist'
          
      - name: Upload Publisher Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: publisher
          path: './dist-publisher'
          
  deploy-main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Main Site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: main-site
          
  deploy-publisher:
    environment:
      name: publisher-pages
      url: http://publisher.transitionmarketingai.com
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Publisher to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: publisher

